version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  express:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    restart: always
    container_name: express_container_SS
    volumes:
      - /api/node_modules
      - type: bind
        source: ./api
        target: /usr/src/api
    develop:
      watch:
        - action: sync
          path: ./api
          target: /usr/src/api
          ignore:
            - node_modules/

  react:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    container_name: react_container_SS
    volumes:
      - /user/app/node_modules
      - type: bind
        source: ./app
        target: /usr/src/app
    develop:
      watch:
        - action: sync
          path: ./app
          target: /usr/src/app
          ignore:
            - node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    stdin_open: true  # Keeps the container open
    tty: true         # Enables a terminal interface for hot reload

volumes:
  postgres_data:
